const BASE_URL = 'https://rravymblcclcuknwubnv.supabase.co/storage/v1/object/public/heinickedevelop/nuxtdemo1'

export default defineEventHandler(() => {
  return [
    {
      id: 1,
      name: 'バスクチーズケーキ（ホール）',
      category: 'ホール',
      price: 3800,
      stock: 15,
      sold: 234,
      imageUrl: `${BASE_URL}/bcc.webp`,
      status: 'active',
      rating: 4.8,
    },
    {
      id: 2,
      name: 'リンゴのタルト（ホール）',
      category: 'ホール',
      price: 4200,
      stock: 12,
      sold: 187,
      imageUrl: `${BASE_URL}/app.webp`,
      status: 'active',
      rating: 4.7,
    },
    {
      id: 3,
      name: 'マスカットのタルト（ホール）',
      category: 'ホール',
      price: 4800,
      stock: 8,
      sold: 142,
      imageUrl: `${BASE_URL}/mus.webp`,
      status: 'active',
      rating: 4.9,
    },
    {
      id: 4,
      name: 'チーズケーキ（ホール）',
      category: 'ホール',
      price: 3500,
      stock: 20,
      sold: 298,
      imageUrl: `${BASE_URL}/cca.webp`,
      status: 'active',
      rating: 4.6,
    },
    {
      id: 5,
      name: 'いちごとブルーベリーのタルト（ホール）',
      category: 'ホール',
      price: 4500,
      stock: 10,
      sold: 165,
      imageUrl: `${BASE_URL}/it.webp`,
      status: 'active',
      rating: 4.8,
    },
    {
      id: 6,
      name: 'フルーツサンド（単品）',
      category: '単品',
      price: 680,
      stock: 45,
      sold: 512,
      imageUrl: `${BASE_URL}/fr.webp`,
      status: 'active',
      rating: 4.5,
    },
    {
      id: 7,
      name: 'いちごのエクレア（単品）',
      category: '単品',
      price: 580,
      stock: 38,
      sold: 423,
      imageUrl: `${BASE_URL}/irc.webp`,
      status: 'active',
      rating: 4.6,
    },
    {
      id: 8,
      name: 'いちごのショートケーキ（単品）',
      category: '単品',
      price: 750,
      stock: 52,
      sold: 634,
      imageUrl: `${BASE_URL}/isc.webp`,
      status: 'active',
      rating: 4.9,
    },
    {
      id: 9,
      name: '栗のモンブラン（単品）',
      category: '単品',
      price: 820,
      stock: 30,
      sold: 389,
      imageUrl: `${BASE_URL}/mon.webp`,
      status: 'active',
      rating: 4.7,
    },
    {
      id: 10,
      name: 'レアチーズケーキ（単品）',
      category: '単品',
      price: 650,
      stock: 42,
      sold: 478,
      imageUrl: `${BASE_URL}/ncca.webp`,
      status: 'inactive',
      rating: 4.5,
    },
  ]
})
