const BASE_URL = 'https://rravymblcclcuknwubnv.supabase.co/storage/v1/object/public/heinickedevelop/nuxtdemo1'

export default defineEventHandler(() => {
  return [
    {
      id: 1,
      name: '田中 さくら',
      email: 'sakura.tanaka@example.com',
      role: 'admin',
      status: 'active',
      joinedAt: '2023-04-01',
      totalOrders: 0,
      totalSpent: 0,
      avatarUrl: `${BASE_URL}/2.webp`,
    },
    {
      id: 2,
      name: '佐藤 健太',
      email: 'kenta.sato@example.com',
      role: 'staff',
      status: 'active',
      joinedAt: '2023-06-15',
      totalOrders: 0,
      totalSpent: 0,
      avatarUrl: `${BASE_URL}/1.webp`,
    },
    {
      id: 3,
      name: '鈴木 大輔',
      email: 'daisuke.suzuki@example.com',
      role: 'customer',
      status: 'active',
      joinedAt: '2024-01-20',
      totalOrders: 14,
      totalSpent: 32800,
      avatarUrl: `${BASE_URL}/3.webp`,
    },
    {
      id: 4,
      name: '山本 翔',
      email: 'sho.yamamoto@example.com',
      role: 'customer',
      status: 'inactive',
      joinedAt: '2023-09-10',
      totalOrders: 3,
      totalSpent: 8900,
      avatarUrl: `${BASE_URL}/4.webp`,
    },
    {
      id: 5,
      name: '伊藤 美咲',
      email: 'misaki.ito@example.com',
      role: 'staff',
      status: 'active',
      joinedAt: '2024-03-01',
      totalOrders: 0,
      totalSpent: 0,
      avatarUrl: `${BASE_URL}/5.webp`,
    },
    {
      id: 6,
      name: '渡辺 葵',
      email: 'aoi.watanabe@example.com',
      role: 'customer',
      status: 'active',
      joinedAt: '2024-07-22',
      totalOrders: 8,
      totalSpent: 19600,
      avatarUrl: `${BASE_URL}/6.webp`,
    },
  ]
})
